# 프로미스(Promise)

- 자바스크립트 안에 내장되어 있는 객체이다.
- 비동기적인 작업을 수행할 때 콜백 함수를 대신해서 유용하게 쓰인다.
- 프로미스는 비동기 처리가 어떻게 진행되고 있는지를 나타내는 상태 정보를 갖는다

  1.pending(비동기 처리가 아직 수행되지 않는 상태)  
  2.fulfilled(수행 성공) : resolve 함수를 호출한다.  
  3.rejected(수행 실패) : reject 함수를 호출한다.   
     -> fulfilled, rejected 상태를 settled 상태라고 한다.  
     pending 상태에선 다른 상태로 변화할 수 있지만 settled 상태가 되면 다른 상태로 변화할 수 없다.

### 프로미스 생성

- 프로미스는 클래스라 객체를 먼저 생성한다.
- 인자로 콜백 함수를 전달한다. 그 안에서 또 resolve, reject 함수를 전달한다.

```javascript
// new 연산자로 프로미스 객체 생성
const promise = new Promise((resolve, reject) => {
  console.log("doing something...");
  setTimeout(() => {
    resolve("sage"); // 수행 성공 시->resolve 콜백 함수 실행
    reject(new Error("no network")); // 수행 실패 시-> reject 콜백 함수 실행
  }, 2000);
});
```

### 프로미스 후속 처리 메소드(then, catch, finally)

- 프로미스의 처리 상태가 변화하면 이에 따른 후속 처리를 해야한다.  
  -> 후속 처리 메소드에 인수로 전달한 콜백 함수가 선택적으로 호출된다
- then, catch, finally 메소드는 값을 바로 전달 하거나 프로미스를 반환한다.

#### then 메소드

- 두 개의 콜백 함수를 인수로 전달받는다.
- 첫 번째는 성공 처리 콜백 함수이고 두 번째는 실패 처리 콜백 함수이다.

#### catch 메소드

- 하나의 콜백 함수를 인수로 전달 받는다.
- 수행 실패 상태인 경우에 호출 된다.

#### finally 메소드

- 성공이나 실패에 상관 없이 무조건 한 번 호출된다.  
  ->프로미스의 상태와 상관없이 공통적으로 수행해야 할 처리 내용이 있을 때 유용하다.

```javascript
const promise = new Promise((resolve, reject) => {
  console.log("doing something...");
  setTimeout(() => {
    resolve("sage");
    reject(new Error("no network"));
  }, 2000);
}); // 'doing something...' 출력

promise
  .then((value) => {
    console.log(value); // resolve()의 인자로 넣어준 값이 value로 할당된다.
  })
  .catch((error) => {
    // reject인 상태가 되면 출력된다.
    console.log(error);
  })
  .finally(() => {
    console.log("finally");
  });
// 'sage'
// 'finally' 출력
```
### 프로미스 체이닝(promise chaining)

- then, catch, finally 메소드는 프로미스를 반환하므로 연속적으로 호출할 수 있다.  
  이를 프로미스 체이닝(promise chaining)이라 한다.

```javascript
const fetchNum = new Promise((resolve, reject) => {
  setTimeout(resolve(1), reject(new Error("no network")), 1000);
});

// then 메소드를 연속적으로 호출할 수 있다
fetchNum
  .then((num) => num * 2) // 2
  .then((num) => num * 3) // 6
  .then((num) => {
    return new Promise((resolve, reject) => {
      setTimeout(() => resolve(num - 1), 1000);
    }); // 5
  })
  .then((num) => console.log(num)) // 콘솔에 5출력
  .catch((error) => console.log(error));
```

### 프로미스 에러 처리(error handling)

- then 메소드의 두 번째 콜백 함수로 처리하거나 catch 메소드를 이용할 수도 있다.
- then 메소드의 두 번째 콜백 함수는 첫 번째 콜백 함수의 에러를 캐치하지 못하고 코드가 복잡해질 수 있다.  
  -> catch 메소드를 then 메소드가 모두 호출된 이후에 호출하면 reject 상태 뿐만 아니라  
   then 메소드 내부에서 발생한 에러까지 모두 캐칠할 수 있다.(권장)

```javascript
// 에러가 나지 않은 상태의 프로미스
const getHen = () =>
  new Promise((resolve, reject) => {
    setTimeout(() => resolve("Hen"), 1000);
  });

const getEgg = (hen) =>
  new Promise((resolve, reject) => {
    setTimeout(() => resolve(`${hen}=>Egg`), 1000);
  });

const cook = (egg) =>
  new Promise((resolve, reject) => {
    setTimeout(() => resolve(`${egg}=>fried`), 1000);
  });

getHen()
  .then((hen) => getEgg(hen))
  .then((egg) => cook(egg))
  .then((meal) => console.log(meal)); // -> Hen=>Egg=>fried
```

```javascript
// p.s) 콜백 함수를 호출할 때 받아오는 값이 하나이고 바로 호출한다면 인자를 생략할 수 있다.
getHen() //
  .then(getEgg)
  .then(cook)
  .then(console.log); // Hen=>Egg=>fried (결과는 같음)
```

```javascript
const getHen = () =>
  new Promise((resolve, reject) => {
    setTimeout(() => resolve("Hen"), 1000);
  });

// 임의로 에러를 발생 시킨다
const getEgg = (hen) =>
  new Promise((resolve, reject) => {
    setTimeout(() => reject(new Error(`Error! ${hen}=>Egg`)), 1000);
  });

const cook = (egg) =>
  new Promise((resolve, reject) => {
    setTimeout(() => resolve(`${egg}=>fried`), 1000);
  });

getHen() //
  .then(getEgg) // getEgg에서 발생한 에러는 바로 다음에 catch를 호출해서 처리할 수 있다.
  .catch((error) => {
    // 전체적인 프로미스 체인에 문제가 생기지 않도록 에러 처리를 해준다
    return "bread";
  })
  .then(cook)
  .then(console.log); // bread=>fried
```
